Fix numpy error with array edge_width in Markers
vispy/vispy pull request #2285
Opened 2022-01-21 15:59 UTC by brisvag

When passing an array to `Markers.edge_width`, a `ValueError` is raised:

```python
    if edge_width < 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

This PR fixes this by using `np.all`.

Also, if a `list` is passed, the comparison fails because

```python
TypeError: '<' not supported between instances of 'list' and 'int'
```

Therefore, I added a line to cast to array first.

2022-01-21 16:29 UTC, djhoese requested changes
:confused: How did this ever work?

2022-01-21 16:29 UTC, djhoese commented on vispy/visuals/markers.py
> +            if np.all(edge_width < 0):
Should be `np.any` shouldn't it?

2022-01-21 16:31 UTC, brisvag commented
> :confused: How did this ever work?

We don't use it yet in napari; also, I think it became an error recently and used to be a warning.

2022-01-21 16:33 UTC, djhoese commented
Can you add a test?

2022-01-21 18:10 UTC, brisvag commented
Is build wheels stuck?

2022-01-21 18:59 UTC, djhoese commented
I'll restart it.

2022-01-23 01:59 UTC, djhoese commented
Looking at the raw log it looks like the Python 3.8 wheels hang when they are being tested. In the past I've seen wheel builds hang/fail when dependency wheels aren't available (like numpy) and the CI job here tries to build the package from source. But in this case this is Python 3.8 and happening during the testing. I guess I'd assume it is some dependency causing the hang up, but I'm not really sure where to go from here.

2022-01-23 11:44 UTC, brisvag commented
Yeah... Odd :/

2022-01-24 09:06 UTC, almarklein approved these changes

2022-01-24 18:13 UTC, merged