Complex volume visual
vispy/vispy pull request #2314
Opened 2022-03-26 22:17 UTC by tlambert03

Follow up to #1999, which would add support for complex valued data to volumes as well.  WIP... includes #1999.  leaving as draft for now until that one merges.

2023-05-03 11:10 UTC, roflmaostc commented
Is there some progress :)?
It's really one feature which would make Napari really great!

2023-10-19 15:04 UTC, roflmaostc commented
Just wanted to follow-up :smile:

2023-10-19 15:14 UTC, tlambert03 commented
👋 
I'm afraid to say I'm not really working on napari anymore so someone will need to pick this up

2023-10-19 15:24 UTC, roflmaostc commented
Ah, that's sad to hear.

How much of the work is missing to get this done here? Is it just for volumes missing?

2023-10-19 15:29 UTC, tlambert03 commented
I can't remember. I'm not sure it's necessarily work that needs to be done as much as agreement on APIs, etc

2023-10-19 16:09 UTC, tlambert03 commented
I'll resolve the conflicts today

2023-10-19 16:20 UTC, tlambert03 commented
conflicts resolved!

2023-10-19 18:24 UTC, djhoese requested changes

2023-10-19 18:24 UTC, djhoese commented on examples/scene/complex_volume.py
> +)
Should this now pass `img_data` and not just the `.real` part?

2023-10-19 18:24 UTC, djhoese commented on examples/scene/complex_volume.py
> +"""
```suggestion
View volume of complex numbers
==============================
"""
```

2023-10-20 12:27 UTC, tlambert03 commented
@brisvag, it would be great if you could pick this up.  I don't really remember the details and am no longer invested in the outcome

2023-10-23 09:22 UTC, brisvag commented
@djhoese what do you think, should this all be ported to `VolumeVisual` to make it handle anything, or should `ComplexVolumeVisual` just handle complex data and that's it?

2023-10-23 11:52 UTC, djhoese commented
I'm not sure how I feel and I'm sure that I've flip flopped on my opinion multiple times over the life of these volume-based PRs. I feel like this feature and its implementation is right on the edge of being too much to add on to the existing `VolumeVisual` but arguably too little for its own Visual. I barely understand the VolumeVisual as it is so this is even harder for me to have an opinion about that I feel comfortable with. I think if someone can implement this functionality in the VolumeVisual and make it understandable/readable then I'm OK with that. In general VisPy's Visuals have too many options as it is so it is hard to justify doing something against that (admittedly bad) design practice or rather it is hard to say "oh but that would be too many kwargs in VolumeVisual" when VisPy does this so much already.

2023-10-23 14:11 UTC, brisvag commented
Now that I look around, I see that we already have the `ComplexImageVisual` which basically follows the same api as this... So maybe for consistency, and given that the `ComplexImage` is already out for a while, it's better to follow the same line.

2023-10-23 14:22 UTC, brisvag commented
Created a new PR at #2539, closing here.

2023-10-23 14:22 UTC, closed without merging