Add lasso selection example.
vispy/vispy pull request #2485
Opened 2023-05-09 21:25 UTC by DanAurea

The example shall allow anyone requiring to use VisPy for lasso selection to be able to have a code reference with a rather complete implementation.

2023-05-10 14:05 UTC, djhoese requested changes
This is a really good start. Thanks for putting this all together. I had a couple comments and suggestions inline. I know there are a couple TODOs so there is still work to do but I wanted to give you feedback.

Some other thoughts: This should maybe be moved to the `scene` examples as it doesn't use the plotting API even though your use case is plotting-adjacent. This tool could be used for any use of Markers (or other visuals).

2023-05-10 20:35 UTC, DanAurea commented
I pushed a cleaned up version of the example following your remarks + further extend optimization reusing matplotlib as a convenience method.
The code is much cleaner right now and easy to understand.

2023-05-12 22:36 UTC, DanAurea reviewed
Change have been performed accordingly + further optimization have been brought.

2023-05-13 01:36 UTC, djhoese commented
This is on my TODO list, but due to other time sensitive things I can't promise I'll get to it immediately. Thanks for putting this all together. @brisvag if you have time and are interested feel free to also review.

2023-05-17 18:13 UTC, djhoese requested changes

2023-05-17 18:13 UTC, djhoese commented on examples/scene/lasso.py
> +from matplotlib import path
It's too bad that this has to depend on matplotlib. It doesn't seem to fail which suggests we have matplotlib in our CI environment. Do we/can we have a fallback of the bounding box implementation if matplotlib isn't available? Perhaps something like:

```
import warnings

try:
    from matplotlib import path
except ImportError:
    warnings.warn("Lasso example requires matplotlib for more accurate selection. Falling back to naive bounding box selection.")
    path = None
```

And then check for `None` later in the code. If you could wrap the bounding box implementation in a path-like function/class that would be even more amazing but I realize this is a big ask.

2023-05-17 18:15 UTC, djhoese commented
Forgot to mention in my review: This is amazing! I'd love to include this in my own application which already includes matplotlib. This example is so smooth. Nice job.

2023-05-17 19:34 UTC, DanAurea commented
> Forgot to mention in my review: This is amazing! I'd love to include this in my own application which already includes matplotlib. This example is so smooth. Nice job.

I used matplotlib since the code used is one of the best compromise in term of performance but yes I could do a rework to add an algorithm without such dependency for sure.

I reworked a bit the code on my side to improve further performance in some situations but yes the lasso itself is very smooth.
I will propose a new commit without matplotlib or at least with a fallback solution.

2023-05-17 22:03 UTC, DanAurea commented
I pushed a commit with fallback solution based on what I had found on Stackoverflow mixed with my bounding box prefiltering this seems to be as smooth as matplotlib based solution.

2023-05-18 01:39 UTC, djhoese commented on examples/scene/lasso.py
> +    Get boolean mask of points in a polygon reusing matplotlib implementation.
```suggestion
    """Get boolean mask of points in a polygon reusing matplotlib implementation.
```

2023-05-18 01:40 UTC, djhoese approved these changes
This looks good to me. I'll give a day or so for @brisvag to provide any other feedback.

2023-05-25 13:23 UTC, brisvag commented
Sorry for the delay, no comments on my side, looks awesome :)

2023-05-25 13:54 UTC, merged

2023-05-25 13:55 UTC, djhoese commented
Thanks @DanAurea. This is great. I'm excited to fit this type of functionality into my own projects.